Add Admin Functionality
aditi-webonise/Room-Booking-System pull request #5
Opened 2017-12-27 13:58 UTC by aditi-webonise

- Add rooms
- Delete rooms
- Update Rooms
- Book room

2017-12-28 06:45 UTC, akshaym-webonise commented on src/main/java/com/webonise/rbs/controller/RoomController.java
> +    @PostMapping(value = "/save")
Please follow Rest APIs conventions 
http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api

2017-12-28 06:46 UTC, akshaym-webonise commented on src/main/java/com/webonise/rbs/controller/RoomController.java
> +        if(operation.equals("delete")) {
What does this method do actually? It seems that it tries to do 2 task according to operation type. Not recommended.

2017-12-28 06:47 UTC, pareekshita-webonise requested changes

2017-12-28 06:47 UTC, pareekshita-webonise commented on pom.xml
> +            <groupId>mysql</groupId>
why same dependency repeated?

2017-12-28 06:47 UTC, pareekshita-webonise commented on pom.xml
> +            <artifactId>nekohtml</artifactId>
what is the use of this dependency?

2017-12-28 06:47 UTC, pareekshita-webonise commented on pom.xml
> +            <artifactId>spring-boot-starter-actuator</artifactId>
again what is the use?

2017-12-28 06:47 UTC, pareekshita-webonise commented on src/main/java/com/webonise/rbs/controller/IndexController.java
> +}
add a blank line to EOF.

2017-12-28 06:47 UTC, pareekshita-webonise commented on src/main/java/com/webonise/rbs/controller/RoomController.java
> +    RoomServiceImpl roomService;
make it private and you have to autowire the interface not the impl class.

2017-12-28 06:47 UTC, pareekshita-webonise commented on src/main/java/com/webonise/rbs/entity/Booking.java
> +@Table(name="bookings")
Table name should be singular.

2017-12-28 06:47 UTC, pareekshita-webonise commented on src/main/java/com/webonise/rbs/controller/RoomController.java
> +    @PostMapping(value = "/update")
for update PUT method is used by convention.

2017-12-28 06:47 UTC, pareekshita-webonise commented on src/main/java/com/webonise/rbs/controller/RoomController.java
> +    public String editRemoveRoom(@PathVariable("operation") String operation, @PathVariable("id") Long id, final RedirectAttributes redirectAttributes, Model model) {
How is deleting a room controller a GET mapping?

2017-12-28 06:47 UTC, pareekshita-webonise commented on src/main/java/com/webonise/rbs/entity/Role.java
> +@Table(name = "roles")
singular table name

2017-12-28 06:47 UTC, pareekshita-webonise commented on src/main/java/com/webonise/rbs/entity/Booking.java
> +    private Long id;
Generation Type??

2017-12-28 06:47 UTC, pareekshita-webonise commented on src/main/java/com/webonise/rbs/service/BookingServiceImpl.java
> +    BookingRepository bookingRepository;
make it private

2017-12-28 06:47 UTC, pareekshita-webonise commented on src/test/java/com/webonise/rbs/RbsApplicationTest.java
>  import org.junit.Test;
do not push commented code. If it is not required then remove it.

2017-12-28 06:47 UTC, pareekshita-webonise commented on src/main/java/com/webonise/rbs/controller/IndexController.java
> +    @GetMapping(value = "/")
no need to specify "/". If you specify then you will get data on "www.abc/" not "www.abc"

2017-12-29 08:50 UTC, pareekshita-webonise approved these changes

2017-12-29 09:17 UTC, merged